networks:
  maxon-network:
    driver: bridge

services:
  zap-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ZAP_API_PORT}:${ZAP_API_PORT}"
    depends_on:
      - zap-db
    networks:
      - maxon-network
    env_file:
      - .env
    command: ["pnpm", "nx", "serve", "zap-api"]

  zap-mini-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ZAP_MINI_APP_PORT}:${ZAP_MINI_APP_PORT}"
    networks:
      - maxon-network
    env_file:
      - .env
    command: ["pnpm", "nx", "serve", "zap-mini-app", "--port", "${ZAP_MINI_APP_PORT}", "--host", "0.0.0.0"]

  zap-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${ZAP_DB_NAME}
      POSTGRES_USER: ${ZAP_DB_USER}
      POSTGRES_PASSWORD: ${ZAP_DB_PASSWORD}
    ports:
      - "${ZAP_DB_PORT}:${ZAP_DB_PORT}"
    networks:
      - maxon-network
